[tool.poetry]
name = "mailing-service"
version = "0.1.0"
description = ""
authors = ["Yelen Prilutskay"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
django = "4.2.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
