# Generated by Django 4.2.2 on 2024-10-15 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Введите имя', max_length=50, verbose_name='Имя клиента')),
                ('midl_name', models.CharField(blank=True, help_text='Введите отчество', max_length=50, null=True, verbose_name='Отчество клиента')),
                ('last_name', models.CharField(help_text='Введите фамилию', max_length=50, verbose_name='Фамилия клиента')),
                ('email', models.EmailField(help_text='Введите контактный email', max_length=150, verbose_name='Email клиента')),
                ('comment', models.TextField(blank=True, help_text='Введите коментарий', null=True, verbose_name='Коментарий')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'ordering': ('last_name',),
            },
        ),
    ]
