# Generated by Django 4.2.2 on 2024-10-25 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_mailingsetup'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailingMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(help_text='Введите тему рассылки', max_length=300, verbose_name='Тема рассылки')),
                ('body', models.TextField(verbose_name='Содержание рассылки')),
            ],
            options={
                'verbose_name': 'Сообщение рассылки',
                'verbose_name_plural': 'Сообщения рассылок',
                'ordering': ('topic',),
            },
        ),
        migrations.AddField(
            model_name='mailingsetup',
            name='message',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='main_app.mailingmessage', verbose_name='Сообщение рассылки'),
        ),
    ]
