# Generated by Django 4.2.2 on 2024-11-05 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_mailingsetup_next_send'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.client', verbose_name='клиент'),
        ),
    ]
