# Generated by Django 4.2.2 on 2024-11-06 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_log_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailingsetup',
            name='is_published',
            field=models.BooleanField(default=True, help_text='Отметьте для активации', verbose_name='Опубликовано'),
        ),
    ]
